import jsPDF from "jspdf";
import type { BusinessPlan } from "./business-plan.functions";

export function exportBusinessPlanPdf(opts: {
  businessName: string;
  idea: string;
  plan: BusinessPlan;
}) {
  const { businessName, idea, plan } = opts;
  const doc = new jsPDF({ unit: "pt", format: "letter" });
  const margin = 56;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const usableWidth = pageWidth - margin * 2;
  let y = margin;

  const ensureSpace = (h: number) => {
    if (y + h > pageHeight - margin) {
      doc.addPage();
      y = margin;
    }
  };
  const text = (str: string, size: number, opts: { bold?: boolean; color?: [number, number, number]; gap?: number } = {}) => {
    doc.setFont("helvetica", opts.bold ? "bold" : "normal");
    doc.setFontSize(size);
    if (opts.color) doc.setTextColor(...opts.color); else doc.setTextColor(20, 20, 30);
    const lines = doc.splitTextToSize(str, usableWidth);
    for (const line of lines) {
      ensureSpace(size + 4);
      doc.text(line, margin, y);
      y += size + 4;
    }
    y += opts.gap ?? 0;
  };
  const heading = (str: string) => {
    y += 10;
    ensureSpace(28);
    doc.setDrawColor(60, 130, 220);
    doc.setLineWidth(2);
    doc.line(margin, y - 4, margin + 36, y - 4);
    text(str, 16, { bold: true, color: [20, 30, 60], gap: 4 });
  };
  const sub = (str: string) => text(str, 11, { bold: true, color: [60, 60, 90], gap: 2 });
  const body = (str: string) => text(str, 10, { gap: 4 });
  const bullets = (items: string[]) => items.forEach((i) => body("• " + i));

  // Cover
  doc.setFillColor(15, 20, 40);
  doc.rect(0, 0, pageWidth, 180, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(28);
  doc.text("Business Plan", margin, 80);
  doc.setFontSize(20);
  doc.text(businessName, margin, 115);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Generated by Startup Validator AI", margin, 140);
  doc.text(new Date().toLocaleDateString(), margin, 156);
  y = 220;
  sub("Idea");
  body(idea);

  // Executive Summary
  heading("1. Executive Summary");
  sub("Overview"); body(plan.executive_summary.overview);
  sub("Mission"); body(plan.executive_summary.mission);
  sub("Vision"); body(plan.executive_summary.vision);
  sub("Objectives"); bullets(plan.executive_summary.objectives);

  // Company
  heading("2. Company Description");
  sub("Legal structure"); body(plan.company_description.legal_structure);
  sub("Location"); body(plan.company_description.location);
  sub("Stage"); body(plan.company_description.stage);
  sub("Team needs"); bullets(plan.company_description.team_needs);

  // Market
  heading("3. Market Analysis");
  sub("Industry overview"); body(plan.market_analysis.industry_overview);
  sub("Target market"); body(plan.market_analysis.target_market);
  sub("Market size estimate"); body(plan.market_analysis.market_size_estimate);
  sub("Customer segments"); bullets(plan.market_analysis.customer_segments);

  // Marketing
  heading("4. Marketing Strategy");
  sub("Positioning"); body(plan.marketing_strategy.positioning);
  sub("Pricing strategy"); body(plan.marketing_strategy.pricing_strategy);
  sub("Acquisition channels"); bullets(plan.marketing_strategy.acquisition_channels);
  sub("Growth tactics"); bullets(plan.marketing_strategy.growth_tactics);

  // Operations
  heading("5. Operations Plan");
  sub("Key activities"); bullets(plan.operations_plan.key_activities);
  sub("Key resources"); bullets(plan.operations_plan.key_resources);
  sub("Tech stack"); bullets(plan.operations_plan.tech_stack);
  sub("Suppliers / partners"); bullets(plan.operations_plan.suppliers_partners);

  // Financial
  heading("6. Financial Plan");
  const fmt = (n: number) => "$" + n.toLocaleString();
  sub("Startup costs"); body(fmt(plan.financial_plan.startup_costs_usd));
  sub("Monthly burn"); body(fmt(plan.financial_plan.monthly_burn_usd));
  sub("Break-even (months)"); body(String(plan.financial_plan.breakeven_months));
  sub("Funding needed"); body(fmt(plan.financial_plan.funding_needed_usd));
  sub("Revenue streams"); bullets(plan.financial_plan.revenue_streams);
  sub("Key assumptions"); bullets(plan.financial_plan.key_assumptions);

  // Milestones
  heading("7. Milestones");
  plan.milestones.forEach((m) => body(`Month ${m.month}: ${m.goal}`));

  // Risks
  heading("8. Risks & Mitigations");
  plan.risks_and_mitigations.forEach((r) => {
    sub("Risk: " + r.risk);
    body("Mitigation: " + r.mitigation);
  });

  doc.save(`${businessName.replace(/[^a-z0-9-_ ]/gi, "")}-business-plan.pdf`);
}
